INSERT INTO AddressPostalCode VALUES ('Vancouver', 'BC', 'V6K 2G8');
INSERT INTO AddressPostalCode VALUES ('Richmond', 'BC', 'V7A 1L9');
INSERT INTO AddressPostalCode VALUES ('Burnaby', 'BC', 'V5B 3A6');
INSERT INTO AddressPostalCode VALUES ('Delta', 'BC', 'V4G 1B6');
INSERT INTO AddressPostalCode VALUES ('Surrey', 'BC', 'V3Z 1E2');
INSERT INTO AddressPostalCode VALUES ('Vancouver', 'BC', 'V6L 3K8');
INSERT INTO AddressPostalCode VALUES ('Calgary', 'AB', 'T2S 0B5');
INSERT INTO AddressPostalCode VALUES ('Toronto', 'ON', 'M4C 1K7');
INSERT INTO AddressPostalCode VALUES ('West Vancouver', 'BC', 'V7W 2N2');
INSERT INTO AddressPostalCode VALUES ('Vancouver', 'BC', 'V6T 1Z4');
INSERT INTO AddressPostalCode VALUES ('Delta', 'BC', 'V4K 3V4');
INSERT INTO AddressPostalCode VALUES ('New Westminster', 'BC', 'V3M 1R8');
